create table IF NOT EXISTS CIDADES  (
    id INT  NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    ESTADO_ID INT UNSIGNED NOT NULL,
    AREA DECIMAL(10,2),
    PRIMARY KEY(ID),
    FOREIGN KEY(ESTADO_ID) REFERENCES ESTADOS (id)
);